export const INCOMES_KEYS = {
  INSERT_WEEKLY_INCOME: 'INSERT_WEEKLY_INCOME',
  INSERT_MONTHLY_INCOME: 'INSERT_MONTHLY_INCOME',
  INSERT_INCOME: 'INSERT_INCOME',
  GET_INCOMES: 'GET_INCOMES',
  GET_INCOME_BY_ID: 'GET_INCOME_BY_ID',
  DELETE_INCOME: 'DELETE_INCOME',
  UPDATE_INCOME: 'UPDATE_INCOME',
  INCOMES_WEEKLY: 'INCOMES_WEEKLY',
  INCOMES_MONTLY: 'INCOMES_MONTLY',
  MONTH_ACTIVITY: 'MONTH_ACTIVITY',
  WEEK_ACTIVITY: 'WEEK_ACTIVITY',
};
